name: gastrulation_multiome_10x_rna_snakemake
channels:
  - conda-forge
  - bioconda
dependencies:
  # - python=3.9.10
  - python=3.8
  - cython
  - ipython
  # - jupyter 
  - ipywidgets
  - bioconductor-scater
  - bioconductor-scran
  - bioconductor-singlecellexperiment
  - bioconductor-batchelor
  - bioconductor-scds
  - bioconductor-edger
  - bioconductor-deseq2
  # - bioconductor-destiny = 3.4 # THIS IS DEPRECIATED, DEPENDS ON bioconductor-singlecellexperiment 1.12
  # - r-xml2 =1.3.2
  - r-r.utils
  - r-matrix
  - r-future
  - r-argparse
  - r-ggpubr
  - r-data.table
  - r-purrr
  - r-furrr
  - r-argparse
  - r-seurat=4.1.0
  - r-pheatmap
  - r-ggrastr
  - scanpy=1.8.2
  - loompy=3.0.6
  - velocyto.py
  # - h5py=2.10.0
  - python-igraph
  - louvain>=0.6,!=0.6.2
  - fa2
  - leidenalg
  - harmonypy
  - scanorama
  - seaborn
  - samtools=1.15
  - snakemake
  - pip
  - pip:
    - dfply
    - scvelo
    - git+https://github.com/settylab/Palantir@removeTSNE
    - git+https://github.com/dpeerlab/SEACells


# conda create -n gastrulation_multiome_10x_rna_snakemake python==3.9 --yes 
# conda activate gastrulation_multiome_10x_rna_snakemake
# conda install mamba --yes
# mamba env update -n gastrulation_multiome_10x_rna_snakemake --file environment.yaml 